server:
  port: 8080

spring:
  application:
    name: mini-store-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/ministore
    username: ministore
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
