server:
  port: 8080

spring:
  application:
    name: mini-store-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/ministore
    username: ministore
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  jwt:
    secret: "CHANGE_ME_DEV_SECRET_CHANGE_ME_DEV_SECRET_123456"
    ttlMinutes: 60
